# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraphDisplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjacencylistfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='adjacencylistfile',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='graphjob',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='graphjob',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
