# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraphDisplay', '0002_auto_20170912_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphjob',
            name='graph_file',
        ),
        migrations.AddField(
            model_name='graphjob',
            name='graph_file',
            field=models.ManyToManyField(to='GraphDisplay.AdjacencyListFile'),
        ),
    ]
