# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraphDisplay', '0003_auto_20170912_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphjob',
            name='status',
            field=models.CharField(default='Not Running', max_length=255),
        ),
    ]
