# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraphDisplay', '0004_auto_20170918_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphjob',
            name='job_input',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
