# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraphDisplay', '0005_graphjob_job_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphjob',
            name='celery_task_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
