# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraphDisplay', '0006_graphjob_celery_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_files', models.ManyToManyField(to='GraphDisplay.ResultFile')),
            ],
        ),
        migrations.AlterField(
            model_name='graphjob',
            name='celery_task_id',
            field=models.TextField(default=''),
        ),
    ]
