# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraphDisplay', '0007_auto_20170926_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='result_files',
        ),
        migrations.RemoveField(
            model_name='resultfile',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='graphjob',
            name='results',
            field=models.ManyToManyField(to='GraphDisplay.ResultFile'),
        ),
        migrations.DeleteModel(
            name='Results',
        ),
    ]
